package model;

// Employee.java
// This class represents a single Employee record.
// It is a simple JavaBean-style class: private fields + public getters/setters.
// This demonstrates ENCAPSULATION (hiding data, exposing it only through methods).

public class Employee {

    // ---- Fields (private = encapsulated) ----
    private int employeeId;
    private String name;
    private String email;
    private String phone;
    private String gender;
    private String dob;          // Date of Birth (stored as String "yyyy-MM-dd" for simplicity)
    private String address;
    private int departmentId;
    private int designationId;
    private String joiningDate;  // "yyyy-MM-dd"
    private double salary;
    private String status;       // "Active" / "Inactive"

    // ---- Constructors ----

    // No-argument constructor (needed when we build the object field by field)
    public Employee() {
    }

    // Constructor WITHOUT employeeId -> used when ADDING a new employee
    // (id is auto-generated by MySQL, so we don't pass it in)
    public Employee(String name, String email, String phone, String gender, String dob,
                     String address, int departmentId, int designationId,
                     String joiningDate, double salary, String status) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.gender = gender;
        this.dob = dob;
        this.address = address;
        this.departmentId = departmentId;
        this.designationId = designationId;
        this.joiningDate = joiningDate;
        this.salary = salary;
        this.status = status;
    }

    // Constructor WITH employeeId -> used when READING an employee from the database
    // This is METHOD OVERLOADING (two constructors, same name, different parameters).
    public Employee(int employeeId, String name, String email, String phone, String gender, String dob,
                     String address, int departmentId, int designationId,
                     String joiningDate, double salary, String status) {
        this(name, email, phone, gender, dob, address, departmentId, designationId, joiningDate, salary, status);
        this.employeeId = employeeId;
    }

    // ---- Getters and Setters (this IS the encapsulation) ----

    public int getEmployeeId() { return employeeId; }
    public void setEmployeeId(int employeeId) { this.employeeId = employeeId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public String getGender() { return gender; }
    public void setGender(String gender) { this.gender = gender; }

    public String getDob() { return dob; }
    public void setDob(String dob) { this.dob = dob; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }

    public int getDepartmentId() { return departmentId; }
    public void setDepartmentId(int departmentId) { this.departmentId = departmentId; }

    public int getDesignationId() { return designationId; }
    public void setDesignationId(int designationId) { this.designationId = designationId; }

    public String getJoiningDate() { return joiningDate; }
    public void setJoiningDate(String joiningDate) { this.joiningDate = joiningDate; }

    public double getSalary() { return salary; }
    public void setSalary(double salary) { this.salary = salary; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", department=" + departmentId +
                ", designation=" + designationId +
                ", salary=" + salary +
                ", status='" + status + '\'' +
                '}';
    }
}
